# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ndk/appid_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ndk import sdk_common_pb2 as ndk_dot_sdk__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17ndk/appid_service.proto\x12\x0bsrlinux.sdk\x1a\x14ndk/sdk_common.proto\"D\n\x1b\x41ppIdentSubscriptionRequest\x12%\n\x03key\x18\x01 \x01(\x0b\x32\x18.srlinux.sdk.AppIdentKey\"\x19\n\x0b\x41ppIdentKey\x12\n\n\x02id\x18\x01 \x01(\r\"S\n\x0c\x41ppIdentData\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x14\n\x0cis_connected\x18\x03 \x01(\x08\x12\x0f\n\x07version\x18\x04 \x01(\t\"\x90\x01\n\x14\x41ppIdentNotification\x12(\n\x02op\x18\x01 \x01(\x0e\x32\x1c.srlinux.sdk.SdkMgrOperation\x12%\n\x03key\x18\x02 \x01(\x0b\x32\x18.srlinux.sdk.AppIdentKey\x12\'\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x19.srlinux.sdk.AppIdentDataB%Z#github.com/nokia/srlinux-ndk-go/ndkb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ndk.appid_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z#github.com/nokia/srlinux-ndk-go/ndk'
  _globals['_APPIDENTSUBSCRIPTIONREQUEST']._serialized_start=62
  _globals['_APPIDENTSUBSCRIPTIONREQUEST']._serialized_end=130
  _globals['_APPIDENTKEY']._serialized_start=132
  _globals['_APPIDENTKEY']._serialized_end=157
  _globals['_APPIDENTDATA']._serialized_start=159
  _globals['_APPIDENTDATA']._serialized_end=242
  _globals['_APPIDENTNOTIFICATION']._serialized_start=245
  _globals['_APPIDENTNOTIFICATION']._serialized_end=389
# @@protoc_insertion_point(module_scope)
