# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ndk/bfd_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ndk import sdk_common_pb2 as ndk_dot_sdk__common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ndk/bfd_service.proto',
  package='ndk',
  syntax='proto3',
  serialized_options=b'Z#github.com/nokia/srlinux-ndk-go/ndk',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15ndk/bfd_service.proto\x12\x03ndk\x1a\x14ndk/sdk_common.proto\"L\n\x1d\x42\x66\x64SessionSubscriptionRequest\x12+\n\x03key\x18\x01 \x01(\x0b\x32\x1e.ndk.BfdmgrGeneralSessionKeyPb\"\xd3\x01\n\x19\x42\x66\x64mgrGeneralSessionKeyPb\x12$\n\x04type\x18\x01 \x01(\x0e\x32\x16.ndk.BfdmgrSessionType\x12%\n\x0bsrc_ip_addr\x18\x02 \x01(\x0b\x32\x10.ndk.IpAddressPb\x12%\n\x0b\x64st_ip_addr\x18\x03 \x01(\x0b\x32\x10.ndk.IpAddressPb\x12\x13\n\x0binstance_id\x18\x04 \x01(\r\x12\x16\n\x0einterface_name\x18\x05 \x01(\t\x12\x15\n\ripv6_ll_if_id\x18\x06 \x01(\r\"\xb8\x02\n\x1a\x42\x66\x64mgrGeneralSessionDataPb\x12(\n\x06status\x18\x01 \x01(\x0e\x32\x18.ndk.BfdmgrSessionStatus\x12\x46\n\x08sub_type\x18\x02 \x01(\x0e\x32\x34.ndk.BfdmgrGeneralSessionDataPb.BfdmgrSessionSubType\x12\x11\n\tsrc_if_id\x18\x03 \x01(\r\"\x94\x01\n\x14\x42\x66\x64mgrSessionSubType\x12\x1c\n\x18SESSION_SUB_TYPE_UNKNOWN\x10\x00\x12\x1f\n\x1bSESSION_SUB_TYPE_SINGLE_HOP\x10\x01\x12\x1e\n\x1aSESSION_SUB_TYPE_MULTI_HOP\x10\x02\x12\x1d\n\x19SESSION_SUB_TYPE_MICROBFD\x10\x03\"\x96\x01\n\x16\x42\x66\x64SessionNotification\x12 \n\x02op\x18\x01 \x01(\x0e\x32\x14.ndk.SdkMgrOperation\x12+\n\x03key\x18\x02 \x01(\x0b\x32\x1e.ndk.BfdmgrGeneralSessionKeyPb\x12-\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x1f.ndk.BfdmgrGeneralSessionDataPb*N\n\x13\x42\x66\x64mgrSessionStatus\x12\x0b\n\x07INVALID\x10\x00\x12\x0e\n\nADMIN_DOWN\x10\x01\x12\x08\n\x04\x44OWN\x10\x02\x12\x08\n\x04INIT\x10\x03\x12\x06\n\x02UP\x10\x04*^\n\x11\x42\x66\x64mgrSessionType\x12\x18\n\x14SESSION_TYPE_UNKNOWN\x10\x00\x12\x14\n\x10SESSION_TYPE_P2P\x10\x01\x12\x19\n\x15SESSION_TYPE_MICROBFD\x10\x02\x42%Z#github.com/nokia/srlinux-ndk-go/ndkb\x06proto3'
  ,
  dependencies=[ndk_dot_sdk__common__pb2.DESCRIPTOR,])

_BFDMGRSESSIONSTATUS = _descriptor.EnumDescriptor(
  name='BfdmgrSessionStatus',
  full_name='ndk.BfdmgrSessionStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INVALID', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ADMIN_DOWN', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DOWN', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INIT', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UP', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=812,
  serialized_end=890,
)
_sym_db.RegisterEnumDescriptor(_BFDMGRSESSIONSTATUS)

BfdmgrSessionStatus = enum_type_wrapper.EnumTypeWrapper(_BFDMGRSESSIONSTATUS)
_BFDMGRSESSIONTYPE = _descriptor.EnumDescriptor(
  name='BfdmgrSessionType',
  full_name='ndk.BfdmgrSessionType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SESSION_TYPE_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SESSION_TYPE_P2P', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SESSION_TYPE_MICROBFD', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=892,
  serialized_end=986,
)
_sym_db.RegisterEnumDescriptor(_BFDMGRSESSIONTYPE)

BfdmgrSessionType = enum_type_wrapper.EnumTypeWrapper(_BFDMGRSESSIONTYPE)
INVALID = 0
ADMIN_DOWN = 1
DOWN = 2
INIT = 3
UP = 4
SESSION_TYPE_UNKNOWN = 0
SESSION_TYPE_P2P = 1
SESSION_TYPE_MICROBFD = 2


_BFDMGRGENERALSESSIONDATAPB_BFDMGRSESSIONSUBTYPE = _descriptor.EnumDescriptor(
  name='BfdmgrSessionSubType',
  full_name='ndk.BfdmgrGeneralSessionDataPb.BfdmgrSessionSubType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SESSION_SUB_TYPE_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SESSION_SUB_TYPE_SINGLE_HOP', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SESSION_SUB_TYPE_MULTI_HOP', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SESSION_SUB_TYPE_MICROBFD', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=509,
  serialized_end=657,
)
_sym_db.RegisterEnumDescriptor(_BFDMGRGENERALSESSIONDATAPB_BFDMGRSESSIONSUBTYPE)


_BFDSESSIONSUBSCRIPTIONREQUEST = _descriptor.Descriptor(
  name='BfdSessionSubscriptionRequest',
  full_name='ndk.BfdSessionSubscriptionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ndk.BfdSessionSubscriptionRequest.key', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=128,
)


_BFDMGRGENERALSESSIONKEYPB = _descriptor.Descriptor(
  name='BfdmgrGeneralSessionKeyPb',
  full_name='ndk.BfdmgrGeneralSessionKeyPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='ndk.BfdmgrGeneralSessionKeyPb.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='src_ip_addr', full_name='ndk.BfdmgrGeneralSessionKeyPb.src_ip_addr', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dst_ip_addr', full_name='ndk.BfdmgrGeneralSessionKeyPb.dst_ip_addr', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='instance_id', full_name='ndk.BfdmgrGeneralSessionKeyPb.instance_id', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='interface_name', full_name='ndk.BfdmgrGeneralSessionKeyPb.interface_name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ipv6_ll_if_id', full_name='ndk.BfdmgrGeneralSessionKeyPb.ipv6_ll_if_id', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=342,
)


_BFDMGRGENERALSESSIONDATAPB = _descriptor.Descriptor(
  name='BfdmgrGeneralSessionDataPb',
  full_name='ndk.BfdmgrGeneralSessionDataPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ndk.BfdmgrGeneralSessionDataPb.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sub_type', full_name='ndk.BfdmgrGeneralSessionDataPb.sub_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='src_if_id', full_name='ndk.BfdmgrGeneralSessionDataPb.src_if_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BFDMGRGENERALSESSIONDATAPB_BFDMGRSESSIONSUBTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=345,
  serialized_end=657,
)


_BFDSESSIONNOTIFICATION = _descriptor.Descriptor(
  name='BfdSessionNotification',
  full_name='ndk.BfdSessionNotification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='op', full_name='ndk.BfdSessionNotification.op', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key', full_name='ndk.BfdSessionNotification.key', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='ndk.BfdSessionNotification.data', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=660,
  serialized_end=810,
)

_BFDSESSIONSUBSCRIPTIONREQUEST.fields_by_name['key'].message_type = _BFDMGRGENERALSESSIONKEYPB
_BFDMGRGENERALSESSIONKEYPB.fields_by_name['type'].enum_type = _BFDMGRSESSIONTYPE
_BFDMGRGENERALSESSIONKEYPB.fields_by_name['src_ip_addr'].message_type = ndk_dot_sdk__common__pb2._IPADDRESSPB
_BFDMGRGENERALSESSIONKEYPB.fields_by_name['dst_ip_addr'].message_type = ndk_dot_sdk__common__pb2._IPADDRESSPB
_BFDMGRGENERALSESSIONDATAPB.fields_by_name['status'].enum_type = _BFDMGRSESSIONSTATUS
_BFDMGRGENERALSESSIONDATAPB.fields_by_name['sub_type'].enum_type = _BFDMGRGENERALSESSIONDATAPB_BFDMGRSESSIONSUBTYPE
_BFDMGRGENERALSESSIONDATAPB_BFDMGRSESSIONSUBTYPE.containing_type = _BFDMGRGENERALSESSIONDATAPB
_BFDSESSIONNOTIFICATION.fields_by_name['op'].enum_type = ndk_dot_sdk__common__pb2._SDKMGROPERATION
_BFDSESSIONNOTIFICATION.fields_by_name['key'].message_type = _BFDMGRGENERALSESSIONKEYPB
_BFDSESSIONNOTIFICATION.fields_by_name['data'].message_type = _BFDMGRGENERALSESSIONDATAPB
DESCRIPTOR.message_types_by_name['BfdSessionSubscriptionRequest'] = _BFDSESSIONSUBSCRIPTIONREQUEST
DESCRIPTOR.message_types_by_name['BfdmgrGeneralSessionKeyPb'] = _BFDMGRGENERALSESSIONKEYPB
DESCRIPTOR.message_types_by_name['BfdmgrGeneralSessionDataPb'] = _BFDMGRGENERALSESSIONDATAPB
DESCRIPTOR.message_types_by_name['BfdSessionNotification'] = _BFDSESSIONNOTIFICATION
DESCRIPTOR.enum_types_by_name['BfdmgrSessionStatus'] = _BFDMGRSESSIONSTATUS
DESCRIPTOR.enum_types_by_name['BfdmgrSessionType'] = _BFDMGRSESSIONTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BfdSessionSubscriptionRequest = _reflection.GeneratedProtocolMessageType('BfdSessionSubscriptionRequest', (_message.Message,), {
  'DESCRIPTOR' : _BFDSESSIONSUBSCRIPTIONREQUEST,
  '__module__' : 'ndk.bfd_service_pb2'
  # @@protoc_insertion_point(class_scope:ndk.BfdSessionSubscriptionRequest)
  })
_sym_db.RegisterMessage(BfdSessionSubscriptionRequest)

BfdmgrGeneralSessionKeyPb = _reflection.GeneratedProtocolMessageType('BfdmgrGeneralSessionKeyPb', (_message.Message,), {
  'DESCRIPTOR' : _BFDMGRGENERALSESSIONKEYPB,
  '__module__' : 'ndk.bfd_service_pb2'
  # @@protoc_insertion_point(class_scope:ndk.BfdmgrGeneralSessionKeyPb)
  })
_sym_db.RegisterMessage(BfdmgrGeneralSessionKeyPb)

BfdmgrGeneralSessionDataPb = _reflection.GeneratedProtocolMessageType('BfdmgrGeneralSessionDataPb', (_message.Message,), {
  'DESCRIPTOR' : _BFDMGRGENERALSESSIONDATAPB,
  '__module__' : 'ndk.bfd_service_pb2'
  # @@protoc_insertion_point(class_scope:ndk.BfdmgrGeneralSessionDataPb)
  })
_sym_db.RegisterMessage(BfdmgrGeneralSessionDataPb)

BfdSessionNotification = _reflection.GeneratedProtocolMessageType('BfdSessionNotification', (_message.Message,), {
  'DESCRIPTOR' : _BFDSESSIONNOTIFICATION,
  '__module__' : 'ndk.bfd_service_pb2'
  # @@protoc_insertion_point(class_scope:ndk.BfdSessionNotification)
  })
_sym_db.RegisterMessage(BfdSessionNotification)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
