# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ndk/config_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ndk import sdk_common_pb2 as ndk_dot_sdk__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18ndk/config_service.proto\x12\x0bsrlinux.sdk\x1a\x14ndk/sdk_common.proto\"@\n\x19\x43onfigSubscriptionRequest\x12#\n\x03key\x18\x01 \x01(\x0b\x32\x16.srlinux.sdk.ConfigKey\"E\n\tConfigKey\x12\x0f\n\x07js_path\x18\x01 \x01(\t\x12\x0c\n\x04keys\x18\x02 \x03(\t\x12\x19\n\x11js_path_with_keys\x18\x03 \x01(\t\"9\n\nConfigData\x12\x0e\n\x04json\x18\x01 \x01(\tH\x00\x12\x0e\n\x04\x64\x61ta\x18\x02 \x01(\x0cH\x00\x42\x0b\n\tdata_type\"\x8a\x01\n\x12\x43onfigNotification\x12(\n\x02op\x18\x01 \x01(\x0e\x32\x1c.srlinux.sdk.SdkMgrOperation\x12#\n\x03key\x18\x02 \x01(\x0b\x32\x16.srlinux.sdk.ConfigKey\x12%\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x17.srlinux.sdk.ConfigDataB%Z#github.com/nokia/srlinux-ndk-go/ndkb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ndk.config_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z#github.com/nokia/srlinux-ndk-go/ndk'
  _globals['_CONFIGSUBSCRIPTIONREQUEST']._serialized_start=63
  _globals['_CONFIGSUBSCRIPTIONREQUEST']._serialized_end=127
  _globals['_CONFIGKEY']._serialized_start=129
  _globals['_CONFIGKEY']._serialized_end=198
  _globals['_CONFIGDATA']._serialized_start=200
  _globals['_CONFIGDATA']._serialized_end=257
  _globals['_CONFIGNOTIFICATION']._serialized_start=260
  _globals['_CONFIGNOTIFICATION']._serialized_end=398
# @@protoc_insertion_point(module_scope)
