# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ndk/interface_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ndk import sdk_common_pb2 as ndk_dot_sdk__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bndk/interface_service.proto\x12\x0bsrlinux.sdk\x1a\x14ndk/sdk_common.proto\"F\n\x1cInterfaceSubscriptionRequest\x12&\n\x03key\x18\x01 \x01(\x0b\x32\x19.srlinux.sdk.InterfaceKey\"\x1f\n\x0cInterfaceKey\x12\x0f\n\x07if_name\x18\x01 \x01(\t\"\xf0\x01\n\rInterfaceData\x12\x13\n\x0b\x61\x64min_is_up\x18\x01 \x01(\r\x12\x0b\n\x03mtu\x18\x02 \x01(\r\x12)\n\x07if_type\x18\x03 \x01(\x0e\x32\x18.srlinux.sdk.IfMgrIfType\x12&\n\x07port_id\x18\x04 \x01(\x0b\x32\x15.srlinux.sdk.PortIdPb\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12+\n\x08mac_addr\x18\x06 \x01(\x0b\x32\x19.srlinux.sdk.MacAddressPb\x12\x14\n\x0c\x61ggregate_id\x18\x07 \x01(\t\x12\x12\n\noper_is_up\x18\x08 \x01(\r\"\x93\x01\n\x15InterfaceNotification\x12(\n\x02op\x18\x01 \x01(\x0e\x32\x1c.srlinux.sdk.SdkMgrOperation\x12&\n\x03key\x18\x02 \x01(\x0b\x32\x19.srlinux.sdk.InterfaceKey\x12(\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x1a.srlinux.sdk.InterfaceDataB%Z#github.com/nokia/srlinux-ndk-go/ndkb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ndk.interface_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z#github.com/nokia/srlinux-ndk-go/ndk'
  _INTERFACESUBSCRIPTIONREQUEST._serialized_start=66
  _INTERFACESUBSCRIPTIONREQUEST._serialized_end=136
  _INTERFACEKEY._serialized_start=138
  _INTERFACEKEY._serialized_end=169
  _INTERFACEDATA._serialized_start=172
  _INTERFACEDATA._serialized_end=412
  _INTERFACENOTIFICATION._serialized_start=415
  _INTERFACENOTIFICATION._serialized_end=562
# @@protoc_insertion_point(module_scope)
