# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ndk/lldp_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ndk import sdk_common_pb2 as ndk_dot_sdk__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16ndk/lldp_service.proto\x12\x0bsrlinux.sdk\x1a\x14ndk/sdk_common.proto\"N\n\x1fLldpNeighborSubscriptionRequest\x12+\n\x03key\x18\x01 \x01(\x0b\x32\x1e.srlinux.sdk.LldpNeighborKeyPb\"\xb3\x02\n\x11LldpNeighborKeyPb\x12\x16\n\x0einterface_name\x18\x01 \x01(\t\x12\x12\n\nchassis_id\x18\x02 \x01(\t\x12\x42\n\x0c\x63hassis_type\x18\x03 \x01(\x0e\x32,.srlinux.sdk.LldpNeighborKeyPb.ChassisIdType\"\xad\x01\n\rChassisIdType\x12\x0c\n\x08RESERVED\x10\x00\x12\x15\n\x11\x43HASSIS_COMPONENT\x10\x01\x12\x13\n\x0fINTERFACE_ALIAS\x10\x02\x12\x12\n\x0ePORT_COMPONENT\x10\x03\x12\x0f\n\x0bMAC_ADDRESS\x10\x04\x12\x13\n\x0fNETWORK_ADDRESS\x10\x05\x12\x12\n\x0eINTERFACE_NAME\x10\x06\x12\x14\n\x10LOCALLY_ASSIGNED\x10\x07\"\xbc\x03\n\x12LldpNeighborDataPb\x12\x0f\n\x07port_id\x18\x01 \x01(\t\x12>\n\tport_type\x18\x02 \x01(\x0e\x32+.srlinux.sdk.LldpNeighborDataPb.PortSubType\x12-\n\nsource_mac\x18\x03 \x01(\x0b\x32\x19.srlinux.sdk.MacAddressPb\x12\x32\n\x10\x62gp_peer_address\x18\x04 \x03(\x0b\x32\x18.srlinux.sdk.IpAddressPb\x12\x14\n\x0c\x62gp_group_id\x18\x05 \x01(\r\x12\x13\n\x0bsystem_name\x18\x06 \x01(\t\x12\x1a\n\x12system_description\x18\x07 \x01(\t\"\xaa\x01\n\x0bPortSubType\x12\x0c\n\x08RESERVED\x10\x00\x12\x13\n\x0fINTERFACE_ALIAS\x10\x01\x12\x12\n\x0ePORT_COMPONENT\x10\x02\x12\x0f\n\x0bMAC_ADDRESS\x10\x03\x12\x13\n\x0fNETWORK_ADDRESS\x10\x04\x12\x12\n\x0eINTERFACE_NAME\x10\x05\x12\x14\n\x10\x41GENT_CIRCUIT_ID\x10\x06\x12\x14\n\x10LOCALLY_ASSIGNED\x10\x07\"\xa0\x01\n\x18LldpNeighborNotification\x12(\n\x02op\x18\x01 \x01(\x0e\x32\x1c.srlinux.sdk.SdkMgrOperation\x12+\n\x03key\x18\x02 \x01(\x0b\x32\x1e.srlinux.sdk.LldpNeighborKeyPb\x12-\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x1f.srlinux.sdk.LldpNeighborDataPbB%Z#github.com/nokia/srlinux-ndk-go/ndkb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ndk.lldp_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z#github.com/nokia/srlinux-ndk-go/ndk'
  _globals['_LLDPNEIGHBORSUBSCRIPTIONREQUEST']._serialized_start=61
  _globals['_LLDPNEIGHBORSUBSCRIPTIONREQUEST']._serialized_end=139
  _globals['_LLDPNEIGHBORKEYPB']._serialized_start=142
  _globals['_LLDPNEIGHBORKEYPB']._serialized_end=449
  _globals['_LLDPNEIGHBORKEYPB_CHASSISIDTYPE']._serialized_start=276
  _globals['_LLDPNEIGHBORKEYPB_CHASSISIDTYPE']._serialized_end=449
  _globals['_LLDPNEIGHBORDATAPB']._serialized_start=452
  _globals['_LLDPNEIGHBORDATAPB']._serialized_end=896
  _globals['_LLDPNEIGHBORDATAPB_PORTSUBTYPE']._serialized_start=726
  _globals['_LLDPNEIGHBORDATAPB_PORTSUBTYPE']._serialized_end=896
  _globals['_LLDPNEIGHBORNOTIFICATION']._serialized_start=899
  _globals['_LLDPNEIGHBORNOTIFICATION']._serialized_end=1059
# @@protoc_insertion_point(module_scope)
