# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ndk/mpls_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ndk import sdk_common_pb2 as ndk_dot_sdk__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16ndk/mpls_service.proto\x12\x0bsrlinux.sdk\x1a\x14ndk/sdk_common.proto\"R\n\x0eMplsRouteKeyPb\x12)\n\ttop_label\x18\x01 \x01(\x0b\x32\x16.srlinux.sdk.MplsLabel\x12\x15\n\rnet_inst_name\x18\x02 \x01(\t\"\xa4\x01\n\x0bMplsRoutePb\x12\x1a\n\x12nexthop_group_name\x18\x01 \x01(\t\x12\x35\n\toperation\x18\x02 \x01(\x0e\x32\".srlinux.sdk.MplsRoutePb.Operation\x12\x12\n\npreference\x18\x03 \x01(\r\".\n\tOperation\x12\x0e\n\nINVALID_OP\x10\x00\x12\x07\n\x03POP\x10\x01\x12\x08\n\x04SWAP\x10\x02\"a\n\rMplsRouteInfo\x12(\n\x03key\x18\x01 \x01(\x0b\x32\x1b.srlinux.sdk.MplsRouteKeyPb\x12&\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x18.srlinux.sdk.MplsRoutePb\"A\n\x13MplsRouteAddRequest\x12*\n\x06routes\x18\x02 \x03(\x0b\x32\x1a.srlinux.sdk.MplsRouteInfo\"T\n\x14MplsRouteAddResponse\x12)\n\x06status\x18\x01 \x01(\x0e\x32\x19.srlinux.sdk.SdkMgrStatus\x12\x11\n\terror_str\x18\x02 \x01(\t\"E\n\x16MplsRouteDeleteRequest\x12+\n\x06routes\x18\x02 \x03(\x0b\x32\x1b.srlinux.sdk.MplsRouteKeyPb\"W\n\x17MplsRouteDeleteResponse\x12)\n\x06status\x18\x01 \x01(\x0e\x32\x19.srlinux.sdk.SdkMgrStatus\x12\x11\n\terror_str\x18\x02 \x01(\t2\xe3\x02\n\x16SdkMgrMplsRouteService\x12`\n\x14MplsRouteAddOrUpdate\x12 .srlinux.sdk.MplsRouteAddRequest\x1a!.srlinux.sdk.MplsRouteAddResponse\"\x03\x88\x02\x01\x12\x61\n\x0fMplsRouteDelete\x12#.srlinux.sdk.MplsRouteDeleteRequest\x1a$.srlinux.sdk.MplsRouteDeleteResponse\"\x03\x88\x02\x01\x12\x42\n\tSyncStart\x12\x18.srlinux.sdk.SyncRequest\x1a\x19.srlinux.sdk.SyncResponse\"\x00\x12@\n\x07SyncEnd\x12\x18.srlinux.sdk.SyncRequest\x1a\x19.srlinux.sdk.SyncResponse\"\x00\x42%Z#github.com/nokia/srlinux-ndk-go/ndkb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ndk.mpls_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z#github.com/nokia/srlinux-ndk-go/ndk'
  _SDKMGRMPLSROUTESERVICE.methods_by_name['MplsRouteAddOrUpdate']._options = None
  _SDKMGRMPLSROUTESERVICE.methods_by_name['MplsRouteAddOrUpdate']._serialized_options = b'\210\002\001'
  _SDKMGRMPLSROUTESERVICE.methods_by_name['MplsRouteDelete']._options = None
  _SDKMGRMPLSROUTESERVICE.methods_by_name['MplsRouteDelete']._serialized_options = b'\210\002\001'
  _MPLSROUTEKEYPB._serialized_start=61
  _MPLSROUTEKEYPB._serialized_end=143
  _MPLSROUTEPB._serialized_start=146
  _MPLSROUTEPB._serialized_end=310
  _MPLSROUTEPB_OPERATION._serialized_start=264
  _MPLSROUTEPB_OPERATION._serialized_end=310
  _MPLSROUTEINFO._serialized_start=312
  _MPLSROUTEINFO._serialized_end=409
  _MPLSROUTEADDREQUEST._serialized_start=411
  _MPLSROUTEADDREQUEST._serialized_end=476
  _MPLSROUTEADDRESPONSE._serialized_start=478
  _MPLSROUTEADDRESPONSE._serialized_end=562
  _MPLSROUTEDELETEREQUEST._serialized_start=564
  _MPLSROUTEDELETEREQUEST._serialized_end=633
  _MPLSROUTEDELETERESPONSE._serialized_start=635
  _MPLSROUTEDELETERESPONSE._serialized_end=722
  _SDKMGRMPLSROUTESERVICE._serialized_start=725
  _SDKMGRMPLSROUTESERVICE._serialized_end=1080
# @@protoc_insertion_point(module_scope)
