# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ndk/mpls_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ndk import sdk_common_pb2 as ndk_dot_sdk__common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ndk/mpls_service.proto',
  package='ndk',
  syntax='proto3',
  serialized_options=b'Z#github.com/nokia/srlinux-ndk-go/ndk',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16ndk/mpls_service.proto\x12\x03ndk\x1a\x14ndk/sdk_common.proto\"J\n\x0eMplsRouteKeyPb\x12!\n\ttop_label\x18\x01 \x01(\x0b\x32\x0e.ndk.MplsLabel\x12\x15\n\rnet_inst_name\x18\x02 \x01(\t\"\x9c\x01\n\x0bMplsRoutePb\x12\x1a\n\x12nexthop_group_name\x18\x01 \x01(\t\x12-\n\toperation\x18\x02 \x01(\x0e\x32\x1a.ndk.MplsRoutePb.Operation\x12\x12\n\npreference\x18\x03 \x01(\r\".\n\tOperation\x12\x0e\n\nINVALID_OP\x10\x00\x12\x07\n\x03POP\x10\x01\x12\x08\n\x04SWAP\x10\x02\"Q\n\rMplsRouteInfo\x12 \n\x03key\x18\x01 \x01(\x0b\x32\x13.ndk.MplsRouteKeyPb\x12\x1e\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x10.ndk.MplsRoutePb\"9\n\x13MplsRouteAddRequest\x12\"\n\x06routes\x18\x02 \x03(\x0b\x32\x12.ndk.MplsRouteInfo\"L\n\x14MplsRouteAddResponse\x12!\n\x06status\x18\x01 \x01(\x0e\x32\x11.ndk.SdkMgrStatus\x12\x11\n\terror_str\x18\x02 \x01(\t\"=\n\x16MplsRouteDeleteRequest\x12#\n\x06routes\x18\x02 \x03(\x0b\x32\x13.ndk.MplsRouteKeyPb\"O\n\x17MplsRouteDeleteResponse\x12!\n\x06status\x18\x01 \x01(\x0e\x32\x11.ndk.SdkMgrStatus\x12\x11\n\terror_str\x18\x02 \x01(\t2\xa3\x02\n\x16SdkMgrMplsRouteService\x12P\n\x14MplsRouteAddOrUpdate\x12\x18.ndk.MplsRouteAddRequest\x1a\x19.ndk.MplsRouteAddResponse\"\x03\x88\x02\x01\x12Q\n\x0fMplsRouteDelete\x12\x1b.ndk.MplsRouteDeleteRequest\x1a\x1c.ndk.MplsRouteDeleteResponse\"\x03\x88\x02\x01\x12\x32\n\tSyncStart\x12\x10.ndk.SyncRequest\x1a\x11.ndk.SyncResponse\"\x00\x12\x30\n\x07SyncEnd\x12\x10.ndk.SyncRequest\x1a\x11.ndk.SyncResponse\"\x00\x42%Z#github.com/nokia/srlinux-ndk-go/ndkb\x06proto3'
  ,
  dependencies=[ndk_dot_sdk__common__pb2.DESCRIPTOR,])



_MPLSROUTEPB_OPERATION = _descriptor.EnumDescriptor(
  name='Operation',
  full_name='ndk.MplsRoutePb.Operation',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INVALID_OP', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='POP', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SWAP', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=240,
  serialized_end=286,
)
_sym_db.RegisterEnumDescriptor(_MPLSROUTEPB_OPERATION)


_MPLSROUTEKEYPB = _descriptor.Descriptor(
  name='MplsRouteKeyPb',
  full_name='ndk.MplsRouteKeyPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='top_label', full_name='ndk.MplsRouteKeyPb.top_label', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='net_inst_name', full_name='ndk.MplsRouteKeyPb.net_inst_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=127,
)


_MPLSROUTEPB = _descriptor.Descriptor(
  name='MplsRoutePb',
  full_name='ndk.MplsRoutePb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nexthop_group_name', full_name='ndk.MplsRoutePb.nexthop_group_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='operation', full_name='ndk.MplsRoutePb.operation', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='preference', full_name='ndk.MplsRoutePb.preference', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MPLSROUTEPB_OPERATION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=286,
)


_MPLSROUTEINFO = _descriptor.Descriptor(
  name='MplsRouteInfo',
  full_name='ndk.MplsRouteInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ndk.MplsRouteInfo.key', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='ndk.MplsRouteInfo.data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=369,
)


_MPLSROUTEADDREQUEST = _descriptor.Descriptor(
  name='MplsRouteAddRequest',
  full_name='ndk.MplsRouteAddRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='routes', full_name='ndk.MplsRouteAddRequest.routes', index=0,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=371,
  serialized_end=428,
)


_MPLSROUTEADDRESPONSE = _descriptor.Descriptor(
  name='MplsRouteAddResponse',
  full_name='ndk.MplsRouteAddResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ndk.MplsRouteAddResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_str', full_name='ndk.MplsRouteAddResponse.error_str', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=430,
  serialized_end=506,
)


_MPLSROUTEDELETEREQUEST = _descriptor.Descriptor(
  name='MplsRouteDeleteRequest',
  full_name='ndk.MplsRouteDeleteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='routes', full_name='ndk.MplsRouteDeleteRequest.routes', index=0,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=508,
  serialized_end=569,
)


_MPLSROUTEDELETERESPONSE = _descriptor.Descriptor(
  name='MplsRouteDeleteResponse',
  full_name='ndk.MplsRouteDeleteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ndk.MplsRouteDeleteResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_str', full_name='ndk.MplsRouteDeleteResponse.error_str', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=571,
  serialized_end=650,
)

_MPLSROUTEKEYPB.fields_by_name['top_label'].message_type = ndk_dot_sdk__common__pb2._MPLSLABEL
_MPLSROUTEPB.fields_by_name['operation'].enum_type = _MPLSROUTEPB_OPERATION
_MPLSROUTEPB_OPERATION.containing_type = _MPLSROUTEPB
_MPLSROUTEINFO.fields_by_name['key'].message_type = _MPLSROUTEKEYPB
_MPLSROUTEINFO.fields_by_name['data'].message_type = _MPLSROUTEPB
_MPLSROUTEADDREQUEST.fields_by_name['routes'].message_type = _MPLSROUTEINFO
_MPLSROUTEADDRESPONSE.fields_by_name['status'].enum_type = ndk_dot_sdk__common__pb2._SDKMGRSTATUS
_MPLSROUTEDELETEREQUEST.fields_by_name['routes'].message_type = _MPLSROUTEKEYPB
_MPLSROUTEDELETERESPONSE.fields_by_name['status'].enum_type = ndk_dot_sdk__common__pb2._SDKMGRSTATUS
DESCRIPTOR.message_types_by_name['MplsRouteKeyPb'] = _MPLSROUTEKEYPB
DESCRIPTOR.message_types_by_name['MplsRoutePb'] = _MPLSROUTEPB
DESCRIPTOR.message_types_by_name['MplsRouteInfo'] = _MPLSROUTEINFO
DESCRIPTOR.message_types_by_name['MplsRouteAddRequest'] = _MPLSROUTEADDREQUEST
DESCRIPTOR.message_types_by_name['MplsRouteAddResponse'] = _MPLSROUTEADDRESPONSE
DESCRIPTOR.message_types_by_name['MplsRouteDeleteRequest'] = _MPLSROUTEDELETEREQUEST
DESCRIPTOR.message_types_by_name['MplsRouteDeleteResponse'] = _MPLSROUTEDELETERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MplsRouteKeyPb = _reflection.GeneratedProtocolMessageType('MplsRouteKeyPb', (_message.Message,), {
  'DESCRIPTOR' : _MPLSROUTEKEYPB,
  '__module__' : 'ndk.mpls_service_pb2'
  # @@protoc_insertion_point(class_scope:ndk.MplsRouteKeyPb)
  })
_sym_db.RegisterMessage(MplsRouteKeyPb)

MplsRoutePb = _reflection.GeneratedProtocolMessageType('MplsRoutePb', (_message.Message,), {
  'DESCRIPTOR' : _MPLSROUTEPB,
  '__module__' : 'ndk.mpls_service_pb2'
  # @@protoc_insertion_point(class_scope:ndk.MplsRoutePb)
  })
_sym_db.RegisterMessage(MplsRoutePb)

MplsRouteInfo = _reflection.GeneratedProtocolMessageType('MplsRouteInfo', (_message.Message,), {
  'DESCRIPTOR' : _MPLSROUTEINFO,
  '__module__' : 'ndk.mpls_service_pb2'
  # @@protoc_insertion_point(class_scope:ndk.MplsRouteInfo)
  })
_sym_db.RegisterMessage(MplsRouteInfo)

MplsRouteAddRequest = _reflection.GeneratedProtocolMessageType('MplsRouteAddRequest', (_message.Message,), {
  'DESCRIPTOR' : _MPLSROUTEADDREQUEST,
  '__module__' : 'ndk.mpls_service_pb2'
  # @@protoc_insertion_point(class_scope:ndk.MplsRouteAddRequest)
  })
_sym_db.RegisterMessage(MplsRouteAddRequest)

MplsRouteAddResponse = _reflection.GeneratedProtocolMessageType('MplsRouteAddResponse', (_message.Message,), {
  'DESCRIPTOR' : _MPLSROUTEADDRESPONSE,
  '__module__' : 'ndk.mpls_service_pb2'
  # @@protoc_insertion_point(class_scope:ndk.MplsRouteAddResponse)
  })
_sym_db.RegisterMessage(MplsRouteAddResponse)

MplsRouteDeleteRequest = _reflection.GeneratedProtocolMessageType('MplsRouteDeleteRequest', (_message.Message,), {
  'DESCRIPTOR' : _MPLSROUTEDELETEREQUEST,
  '__module__' : 'ndk.mpls_service_pb2'
  # @@protoc_insertion_point(class_scope:ndk.MplsRouteDeleteRequest)
  })
_sym_db.RegisterMessage(MplsRouteDeleteRequest)

MplsRouteDeleteResponse = _reflection.GeneratedProtocolMessageType('MplsRouteDeleteResponse', (_message.Message,), {
  'DESCRIPTOR' : _MPLSROUTEDELETERESPONSE,
  '__module__' : 'ndk.mpls_service_pb2'
  # @@protoc_insertion_point(class_scope:ndk.MplsRouteDeleteResponse)
  })
_sym_db.RegisterMessage(MplsRouteDeleteResponse)


DESCRIPTOR._options = None

_SDKMGRMPLSROUTESERVICE = _descriptor.ServiceDescriptor(
  name='SdkMgrMplsRouteService',
  full_name='ndk.SdkMgrMplsRouteService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=653,
  serialized_end=944,
  methods=[
  _descriptor.MethodDescriptor(
    name='MplsRouteAddOrUpdate',
    full_name='ndk.SdkMgrMplsRouteService.MplsRouteAddOrUpdate',
    index=0,
    containing_service=None,
    input_type=_MPLSROUTEADDREQUEST,
    output_type=_MPLSROUTEADDRESPONSE,
    serialized_options=b'\210\002\001',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='MplsRouteDelete',
    full_name='ndk.SdkMgrMplsRouteService.MplsRouteDelete',
    index=1,
    containing_service=None,
    input_type=_MPLSROUTEDELETEREQUEST,
    output_type=_MPLSROUTEDELETERESPONSE,
    serialized_options=b'\210\002\001',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SyncStart',
    full_name='ndk.SdkMgrMplsRouteService.SyncStart',
    index=2,
    containing_service=None,
    input_type=ndk_dot_sdk__common__pb2._SYNCREQUEST,
    output_type=ndk_dot_sdk__common__pb2._SYNCRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SyncEnd',
    full_name='ndk.SdkMgrMplsRouteService.SyncEnd',
    index=3,
    containing_service=None,
    input_type=ndk_dot_sdk__common__pb2._SYNCREQUEST,
    output_type=ndk_dot_sdk__common__pb2._SYNCRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SDKMGRMPLSROUTESERVICE)

DESCRIPTOR.services_by_name['SdkMgrMplsRouteService'] = _SDKMGRMPLSROUTESERVICE

# @@protoc_insertion_point(module_scope)
