# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ndk/networkinstance_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ndk import sdk_common_pb2 as ndk_dot_sdk__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!ndk/networkinstance_service.proto\x12\x0bsrlinux.sdk\x1a\x14ndk/sdk_common.proto\"$\n\"NetworkInstanceSubscriptionRequest\"\'\n\x12NetworkInstanceKey\x12\x11\n\tinst_name\x18\x01 \x01(\t\"\xcc\x01\n\x13NetworkInstanceData\x12\x13\n\x0bnet_inst_id\x18\x01 \x01(\r\x12\x11\n\tbase_name\x18\x02 \x01(\t\x12\x12\n\noper_is_up\x18\x04 \x01(\x08\x12\x11\n\trouter_id\x18\x05 \x01(\t\x12?\n\tinst_type\x18\x06 \x01(\x0e\x32,.srlinux.sdk.NetworkInstanceData.NetInstType\"%\n\x0bNetInstType\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x00\x12\t\n\x05L3VRF\x10\x01\"\xa5\x01\n\x1bNetworkInstanceNotification\x12(\n\x02op\x18\x01 \x01(\x0e\x32\x1c.srlinux.sdk.SdkMgrOperation\x12,\n\x03key\x18\x02 \x01(\x0b\x32\x1f.srlinux.sdk.NetworkInstanceKey\x12.\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32 .srlinux.sdk.NetworkInstanceDataB%Z#github.com/nokia/srlinux-ndk-go/ndkb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ndk.networkinstance_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z#github.com/nokia/srlinux-ndk-go/ndk'
  _globals['_NETWORKINSTANCESUBSCRIPTIONREQUEST']._serialized_start=72
  _globals['_NETWORKINSTANCESUBSCRIPTIONREQUEST']._serialized_end=108
  _globals['_NETWORKINSTANCEKEY']._serialized_start=110
  _globals['_NETWORKINSTANCEKEY']._serialized_end=149
  _globals['_NETWORKINSTANCEDATA']._serialized_start=152
  _globals['_NETWORKINSTANCEDATA']._serialized_end=356
  _globals['_NETWORKINSTANCEDATA_NETINSTTYPE']._serialized_start=319
  _globals['_NETWORKINSTANCEDATA_NETINSTTYPE']._serialized_end=356
  _globals['_NETWORKINSTANCENOTIFICATION']._serialized_start=359
  _globals['_NETWORKINSTANCENOTIFICATION']._serialized_end=524
# @@protoc_insertion_point(module_scope)
