# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ndk import nexthop_group_service_pb2 as ndk_dot_nexthop__group__service__pb2
from ndk import sdk_common_pb2 as ndk_dot_sdk__common__pb2


class SdkMgrNextHopGroupServiceStub(object):
    """*
    Represents service for next-hop group operations.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NextHopGroupAddOrUpdate = channel.unary_unary(
                '/ndk.SdkMgrNextHopGroupService/NextHopGroupAddOrUpdate',
                request_serializer=ndk_dot_nexthop__group__service__pb2.NextHopGroupRequest.SerializeToString,
                response_deserializer=ndk_dot_nexthop__group__service__pb2.NextHopGroupResponse.FromString,
                )
        self.NextHopGroupDelete = channel.unary_unary(
                '/ndk.SdkMgrNextHopGroupService/NextHopGroupDelete',
                request_serializer=ndk_dot_nexthop__group__service__pb2.NextHopGroupDeleteRequest.SerializeToString,
                response_deserializer=ndk_dot_nexthop__group__service__pb2.NextHopGroupDeleteResponse.FromString,
                )
        self.SyncStart = channel.unary_unary(
                '/ndk.SdkMgrNextHopGroupService/SyncStart',
                request_serializer=ndk_dot_sdk__common__pb2.SyncRequest.SerializeToString,
                response_deserializer=ndk_dot_sdk__common__pb2.SyncResponse.FromString,
                )
        self.SyncEnd = channel.unary_unary(
                '/ndk.SdkMgrNextHopGroupService/SyncEnd',
                request_serializer=ndk_dot_sdk__common__pb2.SyncRequest.SerializeToString,
                response_deserializer=ndk_dot_sdk__common__pb2.SyncResponse.FromString,
                )


class SdkMgrNextHopGroupServiceServicer(object):
    """*
    Represents service for next-hop group operations.
    """

    def NextHopGroupAddOrUpdate(self, request, context):
        """/ Add or update one or more next-hop groups.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NextHopGroupDelete(self, request, context):
        """/ Delete next-hop group.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncStart(self, request, context):
        """/ Synchronization start to open synchronization operation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncEnd(self, request, context):
        """/ Synchronization end to close synchronization operation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SdkMgrNextHopGroupServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NextHopGroupAddOrUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.NextHopGroupAddOrUpdate,
                    request_deserializer=ndk_dot_nexthop__group__service__pb2.NextHopGroupRequest.FromString,
                    response_serializer=ndk_dot_nexthop__group__service__pb2.NextHopGroupResponse.SerializeToString,
            ),
            'NextHopGroupDelete': grpc.unary_unary_rpc_method_handler(
                    servicer.NextHopGroupDelete,
                    request_deserializer=ndk_dot_nexthop__group__service__pb2.NextHopGroupDeleteRequest.FromString,
                    response_serializer=ndk_dot_nexthop__group__service__pb2.NextHopGroupDeleteResponse.SerializeToString,
            ),
            'SyncStart': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncStart,
                    request_deserializer=ndk_dot_sdk__common__pb2.SyncRequest.FromString,
                    response_serializer=ndk_dot_sdk__common__pb2.SyncResponse.SerializeToString,
            ),
            'SyncEnd': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncEnd,
                    request_deserializer=ndk_dot_sdk__common__pb2.SyncRequest.FromString,
                    response_serializer=ndk_dot_sdk__common__pb2.SyncResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ndk.SdkMgrNextHopGroupService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SdkMgrNextHopGroupService(object):
    """*
    Represents service for next-hop group operations.
    """

    @staticmethod
    def NextHopGroupAddOrUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ndk.SdkMgrNextHopGroupService/NextHopGroupAddOrUpdate',
            ndk_dot_nexthop__group__service__pb2.NextHopGroupRequest.SerializeToString,
            ndk_dot_nexthop__group__service__pb2.NextHopGroupResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NextHopGroupDelete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ndk.SdkMgrNextHopGroupService/NextHopGroupDelete',
            ndk_dot_nexthop__group__service__pb2.NextHopGroupDeleteRequest.SerializeToString,
            ndk_dot_nexthop__group__service__pb2.NextHopGroupDeleteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SyncStart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ndk.SdkMgrNextHopGroupService/SyncStart',
            ndk_dot_sdk__common__pb2.SyncRequest.SerializeToString,
            ndk_dot_sdk__common__pb2.SyncResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SyncEnd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ndk.SdkMgrNextHopGroupService/SyncEnd',
            ndk_dot_sdk__common__pb2.SyncRequest.SerializeToString,
            ndk_dot_sdk__common__pb2.SyncResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
