# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ndk/route_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ndk import nexthop_group_service_pb2 as ndk_dot_nexthop__group__service__pb2
from ndk import sdk_common_pb2 as ndk_dot_sdk__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17ndk/route_service.proto\x12\x0bsrlinux.sdk\x1a\x1fndk/nexthop_group_service.proto\x1a\x14ndk/sdk_common.proto\"Z\n\x08RouteKey\x12\x1d\n\x15network_instance_name\x18\x01 \x01(\t\x12/\n\tip_prefix\x18\x02 \x01(\x0b\x32\x1c.srlinux.sdk.IpAddrPrefLenPb\"\x9b\x01\n\x05Route\x12\x1a\n\x12nexthop_group_name\x18\x01 \x01(\t\x12\x12\n\npreference\x18\x02 \x01(\r\x12\x0e\n\x06metric\x18\x03 \x01(\r\x12&\n\x08nexthops\x18\x04 \x03(\x0b\x32\x14.srlinux.sdk.NextHop\x12\x10\n\x08owner_id\x18\x05 \x01(\r\x12\x18\n\x10nexthop_group_id\x18\x06 \x01(\x04\"Q\n\tRouteInfo\x12\"\n\x03key\x18\x01 \x01(\x0b\x32\x15.srlinux.sdk.RouteKey\x12 \n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x12.srlinux.sdk.Route\"9\n\x0fRouteAddRequest\x12&\n\x06routes\x18\x02 \x03(\x0b\x32\x16.srlinux.sdk.RouteInfo\"P\n\x10RouteAddResponse\x12)\n\x06status\x18\x01 \x01(\x0e\x32\x19.srlinux.sdk.SdkMgrStatus\x12\x11\n\terror_str\x18\x02 \x01(\t\";\n\x12RouteDeleteRequest\x12%\n\x06routes\x18\x02 \x03(\x0b\x32\x15.srlinux.sdk.RouteKey\"S\n\x13RouteDeleteResponse\x12)\n\x06status\x18\x01 \x01(\x0e\x32\x19.srlinux.sdk.SdkMgrStatus\x12\x11\n\terror_str\x18\x02 \x01(\t\"@\n\x1aIpRouteSubscriptionRequest\x12\"\n\x03key\x18\x01 \x01(\x0b\x32\x15.srlinux.sdk.RouteKey\"\x85\x01\n\x13IpRouteNotification\x12(\n\x02op\x18\x01 \x01(\x0e\x32\x1c.srlinux.sdk.SdkMgrOperation\x12\"\n\x03key\x18\x02 \x01(\x0b\x32\x15.srlinux.sdk.RouteKey\x12 \n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x12.srlinux.sdk.Route2\xc1\x02\n\x12SdkMgrRouteService\x12Q\n\x10RouteAddOrUpdate\x12\x1c.srlinux.sdk.RouteAddRequest\x1a\x1d.srlinux.sdk.RouteAddResponse\"\x00\x12R\n\x0bRouteDelete\x12\x1f.srlinux.sdk.RouteDeleteRequest\x1a .srlinux.sdk.RouteDeleteResponse\"\x00\x12\x42\n\tSyncStart\x12\x18.srlinux.sdk.SyncRequest\x1a\x19.srlinux.sdk.SyncResponse\"\x00\x12@\n\x07SyncEnd\x12\x18.srlinux.sdk.SyncRequest\x1a\x19.srlinux.sdk.SyncResponse\"\x00\x42%Z#github.com/nokia/srlinux-ndk-go/ndkb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ndk.route_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z#github.com/nokia/srlinux-ndk-go/ndk'
  _globals['_ROUTEKEY']._serialized_start=95
  _globals['_ROUTEKEY']._serialized_end=185
  _globals['_ROUTE']._serialized_start=188
  _globals['_ROUTE']._serialized_end=343
  _globals['_ROUTEINFO']._serialized_start=345
  _globals['_ROUTEINFO']._serialized_end=426
  _globals['_ROUTEADDREQUEST']._serialized_start=428
  _globals['_ROUTEADDREQUEST']._serialized_end=485
  _globals['_ROUTEADDRESPONSE']._serialized_start=487
  _globals['_ROUTEADDRESPONSE']._serialized_end=567
  _globals['_ROUTEDELETEREQUEST']._serialized_start=569
  _globals['_ROUTEDELETEREQUEST']._serialized_end=628
  _globals['_ROUTEDELETERESPONSE']._serialized_start=630
  _globals['_ROUTEDELETERESPONSE']._serialized_end=713
  _globals['_IPROUTESUBSCRIPTIONREQUEST']._serialized_start=715
  _globals['_IPROUTESUBSCRIPTIONREQUEST']._serialized_end=779
  _globals['_IPROUTENOTIFICATION']._serialized_start=782
  _globals['_IPROUTENOTIFICATION']._serialized_end=915
  _globals['_SDKMGRROUTESERVICE']._serialized_start=918
  _globals['_SDKMGRROUTESERVICE']._serialized_end=1239
# @@protoc_insertion_point(module_scope)
