# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ndk import route_service_pb2 as ndk_dot_route__service__pb2
from ndk import sdk_common_pb2 as ndk_dot_sdk__common__pb2


class SdkMgrRouteServiceStub(object):
    """*
    Represents service for IP route operations.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RouteAddOrUpdate = channel.unary_unary(
                '/srlinux.sdk.SdkMgrRouteService/RouteAddOrUpdate',
                request_serializer=ndk_dot_route__service__pb2.RouteAddRequest.SerializeToString,
                response_deserializer=ndk_dot_route__service__pb2.RouteAddResponse.FromString,
                )
        self.RouteDelete = channel.unary_unary(
                '/srlinux.sdk.SdkMgrRouteService/RouteDelete',
                request_serializer=ndk_dot_route__service__pb2.RouteDeleteRequest.SerializeToString,
                response_deserializer=ndk_dot_route__service__pb2.RouteDeleteResponse.FromString,
                )
        self.SyncStart = channel.unary_unary(
                '/srlinux.sdk.SdkMgrRouteService/SyncStart',
                request_serializer=ndk_dot_sdk__common__pb2.SyncRequest.SerializeToString,
                response_deserializer=ndk_dot_sdk__common__pb2.SyncResponse.FromString,
                )
        self.SyncEnd = channel.unary_unary(
                '/srlinux.sdk.SdkMgrRouteService/SyncEnd',
                request_serializer=ndk_dot_sdk__common__pb2.SyncRequest.SerializeToString,
                response_deserializer=ndk_dot_sdk__common__pb2.SyncResponse.FromString,
                )


class SdkMgrRouteServiceServicer(object):
    """*
    Represents service for IP route operations.
    """

    def RouteAddOrUpdate(self, request, context):
        """/ Add or update IP routes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RouteDelete(self, request, context):
        """/ Delete IP routes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncStart(self, request, context):
        """/ Synchronization start for IP routes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncEnd(self, request, context):
        """/ Synchronization end for IP routes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SdkMgrRouteServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RouteAddOrUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.RouteAddOrUpdate,
                    request_deserializer=ndk_dot_route__service__pb2.RouteAddRequest.FromString,
                    response_serializer=ndk_dot_route__service__pb2.RouteAddResponse.SerializeToString,
            ),
            'RouteDelete': grpc.unary_unary_rpc_method_handler(
                    servicer.RouteDelete,
                    request_deserializer=ndk_dot_route__service__pb2.RouteDeleteRequest.FromString,
                    response_serializer=ndk_dot_route__service__pb2.RouteDeleteResponse.SerializeToString,
            ),
            'SyncStart': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncStart,
                    request_deserializer=ndk_dot_sdk__common__pb2.SyncRequest.FromString,
                    response_serializer=ndk_dot_sdk__common__pb2.SyncResponse.SerializeToString,
            ),
            'SyncEnd': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncEnd,
                    request_deserializer=ndk_dot_sdk__common__pb2.SyncRequest.FromString,
                    response_serializer=ndk_dot_sdk__common__pb2.SyncResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'srlinux.sdk.SdkMgrRouteService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SdkMgrRouteService(object):
    """*
    Represents service for IP route operations.
    """

    @staticmethod
    def RouteAddOrUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srlinux.sdk.SdkMgrRouteService/RouteAddOrUpdate',
            ndk_dot_route__service__pb2.RouteAddRequest.SerializeToString,
            ndk_dot_route__service__pb2.RouteAddResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RouteDelete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srlinux.sdk.SdkMgrRouteService/RouteDelete',
            ndk_dot_route__service__pb2.RouteDeleteRequest.SerializeToString,
            ndk_dot_route__service__pb2.RouteDeleteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SyncStart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srlinux.sdk.SdkMgrRouteService/SyncStart',
            ndk_dot_sdk__common__pb2.SyncRequest.SerializeToString,
            ndk_dot_sdk__common__pb2.SyncResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SyncEnd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srlinux.sdk.SdkMgrRouteService/SyncEnd',
            ndk_dot_sdk__common__pb2.SyncRequest.SerializeToString,
            ndk_dot_sdk__common__pb2.SyncResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
