# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ndk/route_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ndk import sdk_common_pb2 as ndk_dot_sdk__common__pb2
from ndk import nexthop_group_service_pb2 as ndk_dot_nexthop__group__service__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ndk/route_service.proto',
  package='srlinux.sdk',
  syntax='proto3',
  serialized_options=b'Z#github.com/nokia/srlinux-ndk-go/ndk',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17ndk/route_service.proto\x12\x0bsrlinux.sdk\x1a\x14ndk/sdk_common.proto\x1a\x1fndk/nexthop_group_service.proto\"T\n\nRouteKeyPb\x12\x15\n\rnet_inst_name\x18\x01 \x01(\t\x12/\n\tip_prefix\x18\x02 \x01(\x0b\x32\x1c.srlinux.sdk.IpAddrPrefLenPb\"\x92\x01\n\x07RoutePb\x12\x1a\n\x12nexthop_group_name\x18\x01 \x01(\t\x12\x12\n\npreference\x18\x02 \x01(\r\x12\x0e\n\x06metric\x18\x03 \x01(\r\x12%\n\x07nexthop\x18\x04 \x03(\x0b\x32\x14.srlinux.sdk.NextHop\x12\x10\n\x08owner_id\x18\x05 \x01(\r\x12\x0e\n\x06nhg_id\x18\x06 \x01(\x04\"U\n\tRouteInfo\x12$\n\x03key\x18\x01 \x01(\x0b\x32\x17.srlinux.sdk.RouteKeyPb\x12\"\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x14.srlinux.sdk.RoutePb\"9\n\x0fRouteAddRequest\x12&\n\x06routes\x18\x02 \x03(\x0b\x32\x16.srlinux.sdk.RouteInfo\"P\n\x10RouteAddResponse\x12)\n\x06status\x18\x01 \x01(\x0e\x32\x19.srlinux.sdk.SdkMgrStatus\x12\x11\n\terror_str\x18\x02 \x01(\t\"=\n\x12RouteDeleteRequest\x12\'\n\x06routes\x18\x02 \x03(\x0b\x32\x17.srlinux.sdk.RouteKeyPb\"S\n\x13RouteDeleteResponse\x12)\n\x06status\x18\x01 \x01(\x0e\x32\x19.srlinux.sdk.SdkMgrStatus\x12\x11\n\terror_str\x18\x02 \x01(\t\"B\n\x1aIpRouteSubscriptionRequest\x12$\n\x03key\x18\x01 \x01(\x0b\x32\x17.srlinux.sdk.RouteKeyPb\"\x89\x01\n\x13IpRouteNotification\x12(\n\x02op\x18\x01 \x01(\x0e\x32\x1c.srlinux.sdk.SdkMgrOperation\x12$\n\x03key\x18\x02 \x01(\x0b\x32\x17.srlinux.sdk.RouteKeyPb\x12\"\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x14.srlinux.sdk.RoutePb2\xc1\x02\n\x12SdkMgrRouteService\x12Q\n\x10RouteAddOrUpdate\x12\x1c.srlinux.sdk.RouteAddRequest\x1a\x1d.srlinux.sdk.RouteAddResponse\"\x00\x12R\n\x0bRouteDelete\x12\x1f.srlinux.sdk.RouteDeleteRequest\x1a .srlinux.sdk.RouteDeleteResponse\"\x00\x12\x42\n\tSyncStart\x12\x18.srlinux.sdk.SyncRequest\x1a\x19.srlinux.sdk.SyncResponse\"\x00\x12@\n\x07SyncEnd\x12\x18.srlinux.sdk.SyncRequest\x1a\x19.srlinux.sdk.SyncResponse\"\x00\x42%Z#github.com/nokia/srlinux-ndk-go/ndkb\x06proto3'
  ,
  dependencies=[ndk_dot_sdk__common__pb2.DESCRIPTOR,ndk_dot_nexthop__group__service__pb2.DESCRIPTOR,])




_ROUTEKEYPB = _descriptor.Descriptor(
  name='RouteKeyPb',
  full_name='srlinux.sdk.RouteKeyPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='net_inst_name', full_name='srlinux.sdk.RouteKeyPb.net_inst_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ip_prefix', full_name='srlinux.sdk.RouteKeyPb.ip_prefix', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=179,
)


_ROUTEPB = _descriptor.Descriptor(
  name='RoutePb',
  full_name='srlinux.sdk.RoutePb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nexthop_group_name', full_name='srlinux.sdk.RoutePb.nexthop_group_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='preference', full_name='srlinux.sdk.RoutePb.preference', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='metric', full_name='srlinux.sdk.RoutePb.metric', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nexthop', full_name='srlinux.sdk.RoutePb.nexthop', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='owner_id', full_name='srlinux.sdk.RoutePb.owner_id', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nhg_id', full_name='srlinux.sdk.RoutePb.nhg_id', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=328,
)


_ROUTEINFO = _descriptor.Descriptor(
  name='RouteInfo',
  full_name='srlinux.sdk.RouteInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='srlinux.sdk.RouteInfo.key', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='srlinux.sdk.RouteInfo.data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=330,
  serialized_end=415,
)


_ROUTEADDREQUEST = _descriptor.Descriptor(
  name='RouteAddRequest',
  full_name='srlinux.sdk.RouteAddRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='routes', full_name='srlinux.sdk.RouteAddRequest.routes', index=0,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=417,
  serialized_end=474,
)


_ROUTEADDRESPONSE = _descriptor.Descriptor(
  name='RouteAddResponse',
  full_name='srlinux.sdk.RouteAddResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='srlinux.sdk.RouteAddResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_str', full_name='srlinux.sdk.RouteAddResponse.error_str', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=476,
  serialized_end=556,
)


_ROUTEDELETEREQUEST = _descriptor.Descriptor(
  name='RouteDeleteRequest',
  full_name='srlinux.sdk.RouteDeleteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='routes', full_name='srlinux.sdk.RouteDeleteRequest.routes', index=0,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=558,
  serialized_end=619,
)


_ROUTEDELETERESPONSE = _descriptor.Descriptor(
  name='RouteDeleteResponse',
  full_name='srlinux.sdk.RouteDeleteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='srlinux.sdk.RouteDeleteResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_str', full_name='srlinux.sdk.RouteDeleteResponse.error_str', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=621,
  serialized_end=704,
)


_IPROUTESUBSCRIPTIONREQUEST = _descriptor.Descriptor(
  name='IpRouteSubscriptionRequest',
  full_name='srlinux.sdk.IpRouteSubscriptionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='srlinux.sdk.IpRouteSubscriptionRequest.key', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=706,
  serialized_end=772,
)


_IPROUTENOTIFICATION = _descriptor.Descriptor(
  name='IpRouteNotification',
  full_name='srlinux.sdk.IpRouteNotification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='op', full_name='srlinux.sdk.IpRouteNotification.op', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key', full_name='srlinux.sdk.IpRouteNotification.key', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='srlinux.sdk.IpRouteNotification.data', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=775,
  serialized_end=912,
)

_ROUTEKEYPB.fields_by_name['ip_prefix'].message_type = ndk_dot_sdk__common__pb2._IPADDRPREFLENPB
_ROUTEPB.fields_by_name['nexthop'].message_type = ndk_dot_nexthop__group__service__pb2._NEXTHOP
_ROUTEINFO.fields_by_name['key'].message_type = _ROUTEKEYPB
_ROUTEINFO.fields_by_name['data'].message_type = _ROUTEPB
_ROUTEADDREQUEST.fields_by_name['routes'].message_type = _ROUTEINFO
_ROUTEADDRESPONSE.fields_by_name['status'].enum_type = ndk_dot_sdk__common__pb2._SDKMGRSTATUS
_ROUTEDELETEREQUEST.fields_by_name['routes'].message_type = _ROUTEKEYPB
_ROUTEDELETERESPONSE.fields_by_name['status'].enum_type = ndk_dot_sdk__common__pb2._SDKMGRSTATUS
_IPROUTESUBSCRIPTIONREQUEST.fields_by_name['key'].message_type = _ROUTEKEYPB
_IPROUTENOTIFICATION.fields_by_name['op'].enum_type = ndk_dot_sdk__common__pb2._SDKMGROPERATION
_IPROUTENOTIFICATION.fields_by_name['key'].message_type = _ROUTEKEYPB
_IPROUTENOTIFICATION.fields_by_name['data'].message_type = _ROUTEPB
DESCRIPTOR.message_types_by_name['RouteKeyPb'] = _ROUTEKEYPB
DESCRIPTOR.message_types_by_name['RoutePb'] = _ROUTEPB
DESCRIPTOR.message_types_by_name['RouteInfo'] = _ROUTEINFO
DESCRIPTOR.message_types_by_name['RouteAddRequest'] = _ROUTEADDREQUEST
DESCRIPTOR.message_types_by_name['RouteAddResponse'] = _ROUTEADDRESPONSE
DESCRIPTOR.message_types_by_name['RouteDeleteRequest'] = _ROUTEDELETEREQUEST
DESCRIPTOR.message_types_by_name['RouteDeleteResponse'] = _ROUTEDELETERESPONSE
DESCRIPTOR.message_types_by_name['IpRouteSubscriptionRequest'] = _IPROUTESUBSCRIPTIONREQUEST
DESCRIPTOR.message_types_by_name['IpRouteNotification'] = _IPROUTENOTIFICATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RouteKeyPb = _reflection.GeneratedProtocolMessageType('RouteKeyPb', (_message.Message,), {
  'DESCRIPTOR' : _ROUTEKEYPB,
  '__module__' : 'ndk.route_service_pb2'
  # @@protoc_insertion_point(class_scope:srlinux.sdk.RouteKeyPb)
  })
_sym_db.RegisterMessage(RouteKeyPb)

RoutePb = _reflection.GeneratedProtocolMessageType('RoutePb', (_message.Message,), {
  'DESCRIPTOR' : _ROUTEPB,
  '__module__' : 'ndk.route_service_pb2'
  # @@protoc_insertion_point(class_scope:srlinux.sdk.RoutePb)
  })
_sym_db.RegisterMessage(RoutePb)

RouteInfo = _reflection.GeneratedProtocolMessageType('RouteInfo', (_message.Message,), {
  'DESCRIPTOR' : _ROUTEINFO,
  '__module__' : 'ndk.route_service_pb2'
  # @@protoc_insertion_point(class_scope:srlinux.sdk.RouteInfo)
  })
_sym_db.RegisterMessage(RouteInfo)

RouteAddRequest = _reflection.GeneratedProtocolMessageType('RouteAddRequest', (_message.Message,), {
  'DESCRIPTOR' : _ROUTEADDREQUEST,
  '__module__' : 'ndk.route_service_pb2'
  # @@protoc_insertion_point(class_scope:srlinux.sdk.RouteAddRequest)
  })
_sym_db.RegisterMessage(RouteAddRequest)

RouteAddResponse = _reflection.GeneratedProtocolMessageType('RouteAddResponse', (_message.Message,), {
  'DESCRIPTOR' : _ROUTEADDRESPONSE,
  '__module__' : 'ndk.route_service_pb2'
  # @@protoc_insertion_point(class_scope:srlinux.sdk.RouteAddResponse)
  })
_sym_db.RegisterMessage(RouteAddResponse)

RouteDeleteRequest = _reflection.GeneratedProtocolMessageType('RouteDeleteRequest', (_message.Message,), {
  'DESCRIPTOR' : _ROUTEDELETEREQUEST,
  '__module__' : 'ndk.route_service_pb2'
  # @@protoc_insertion_point(class_scope:srlinux.sdk.RouteDeleteRequest)
  })
_sym_db.RegisterMessage(RouteDeleteRequest)

RouteDeleteResponse = _reflection.GeneratedProtocolMessageType('RouteDeleteResponse', (_message.Message,), {
  'DESCRIPTOR' : _ROUTEDELETERESPONSE,
  '__module__' : 'ndk.route_service_pb2'
  # @@protoc_insertion_point(class_scope:srlinux.sdk.RouteDeleteResponse)
  })
_sym_db.RegisterMessage(RouteDeleteResponse)

IpRouteSubscriptionRequest = _reflection.GeneratedProtocolMessageType('IpRouteSubscriptionRequest', (_message.Message,), {
  'DESCRIPTOR' : _IPROUTESUBSCRIPTIONREQUEST,
  '__module__' : 'ndk.route_service_pb2'
  # @@protoc_insertion_point(class_scope:srlinux.sdk.IpRouteSubscriptionRequest)
  })
_sym_db.RegisterMessage(IpRouteSubscriptionRequest)

IpRouteNotification = _reflection.GeneratedProtocolMessageType('IpRouteNotification', (_message.Message,), {
  'DESCRIPTOR' : _IPROUTENOTIFICATION,
  '__module__' : 'ndk.route_service_pb2'
  # @@protoc_insertion_point(class_scope:srlinux.sdk.IpRouteNotification)
  })
_sym_db.RegisterMessage(IpRouteNotification)


DESCRIPTOR._options = None

_SDKMGRROUTESERVICE = _descriptor.ServiceDescriptor(
  name='SdkMgrRouteService',
  full_name='srlinux.sdk.SdkMgrRouteService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=915,
  serialized_end=1236,
  methods=[
  _descriptor.MethodDescriptor(
    name='RouteAddOrUpdate',
    full_name='srlinux.sdk.SdkMgrRouteService.RouteAddOrUpdate',
    index=0,
    containing_service=None,
    input_type=_ROUTEADDREQUEST,
    output_type=_ROUTEADDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RouteDelete',
    full_name='srlinux.sdk.SdkMgrRouteService.RouteDelete',
    index=1,
    containing_service=None,
    input_type=_ROUTEDELETEREQUEST,
    output_type=_ROUTEDELETERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SyncStart',
    full_name='srlinux.sdk.SdkMgrRouteService.SyncStart',
    index=2,
    containing_service=None,
    input_type=ndk_dot_sdk__common__pb2._SYNCREQUEST,
    output_type=ndk_dot_sdk__common__pb2._SYNCRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SyncEnd',
    full_name='srlinux.sdk.SdkMgrRouteService.SyncEnd',
    index=3,
    containing_service=None,
    input_type=ndk_dot_sdk__common__pb2._SYNCREQUEST,
    output_type=ndk_dot_sdk__common__pb2._SYNCRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SDKMGRROUTESERVICE)

DESCRIPTOR.services_by_name['SdkMgrRouteService'] = _SDKMGRROUTESERVICE

# @@protoc_insertion_point(module_scope)
